/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backgroundColor?: "dominant" | "vibrant" | "muted";
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  icon?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "pixel";
  };
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigation?: Array<{
    label?: string;
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    iconType?: "pixel" | "image";
    pixelIcon?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "pixel";
    };
    uploadedIcon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "navLink";
    _key: string;
  }>;
  footerText?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    iconType?: "pixel" | "image";
    pixelIcon?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "pixel";
    };
    uploadedIcon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "socialLink";
    _key: string;
  }>;
};

export type SeoSettings = {
  _id: string;
  _type: "seoSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  defaultTitle?: string;
  defaultDescription?: string;
  defaultOgImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  defaultKeywords?: Array<string>;
  defaultCanonicalUrl?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  slug?: Slug;
  intro?: string;
  pixelPuzzle?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "pixel";
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  keywords?: Array<string>;
  canonicalUrl?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Pixel = {
  _id: string;
  _type: "pixel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  svg?: string;
  json?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Category
  | Article
  | Author
  | SiteSettings
  | SeoSettings
  | Page
  | Seo
  | Pixel
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: queries/article.ts
// Variable: articleQuery
// Query: *[_type == "article" && slug.current == $slug][0]{      title,      author->{        name,        avatar {          asset->{            url          }        },        bio,      },      body,      primaryCta->{        label,          type,      },      coverImage {        asset->{          url,          metadata {            palette {              dominant {                background,                foreground,                population,              },              vibrant {                background,                foreground              },              muted {                background,                foreground              }            },            blurHash          }        }      },      backgroundPalette,      "palettes": {        "dominant": coverImage.asset->metadata.palette.dominant,        "vibrant": coverImage.asset->metadata.palette.vibrant,        "muted": coverImage.asset->metadata.palette.muted      },      isPrivate,      puzzle->{        title,        svg,        json      },      excerpt,      "pixel": icon->svg,      tagGroupSections[]{        heading,        groups[]{          emoji,          tags        }      }    }
export type ArticleQueryResult = {
  title: string | null;
  author: {
    name: string | null;
    avatar: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    bio: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  primaryCta: null;
  coverImage: {
    asset: {
      url: string | null;
      metadata: {
        palette: {
          dominant: {
            background: string | null;
            foreground: string | null;
            population: number | null;
          } | null;
          vibrant: {
            background: string | null;
            foreground: string | null;
          } | null;
          muted: {
            background: string | null;
            foreground: string | null;
          } | null;
        } | null;
        blurHash: string | null;
      } | null;
    } | null;
  } | null;
  backgroundPalette: null;
  palettes: {
    dominant: SanityImagePaletteSwatch | null;
    vibrant: SanityImagePaletteSwatch | null;
    muted: SanityImagePaletteSwatch | null;
  };
  isPrivate: null;
  puzzle: null;
  excerpt: string | null;
  pixel: string | null;
  tagGroupSections: null;
} | null;

// Source: queries/homePage.ts
// Variable: homePageQuery
// Query: *[_type == "page" && slug.current == "/"][0]{  heading,  intro,  "themeColor": {    "h": coalesce(themeColor.hsl.h, 200),    "s": coalesce(themeColor.hsl.s * 100, 100),    "l": coalesce(themeColor.hsl.l * 100, 50)  },  pixelPuzzle->{    title,    svg,    json  },  "articles": *[_type == "article" && references(^._id)]{    _key,    "slug": slug.current,    title,    excerpt,    coverImage {      asset->{        url,        metadata {          palette {            dominant { background, foreground, population },            vibrant { background, foreground },            muted { background, foreground }          },          blurHash        }      }    }  }}
export type HomePageQueryResult = {
  heading: string | null;
  intro: string | null;
  themeColor: {
    h: 200;
    s: 100;
    l: 50;
  };
  pixelPuzzle: {
    title: string | null;
    svg: string | null;
    json: string | null;
  } | null;
  articles: Array<{
    _key: null;
    slug: string | null;
    title: string | null;
    excerpt: string | null;
    coverImage: {
      asset: {
        url: string | null;
        metadata: {
          palette: {
            dominant: {
              background: string | null;
              foreground: string | null;
              population: number | null;
            } | null;
            vibrant: {
              background: string | null;
              foreground: string | null;
            } | null;
            muted: {
              background: string | null;
              foreground: string | null;
            } | null;
          } | null;
          blurHash: string | null;
        } | null;
      } | null;
    } | null;
  }>;
} | null;

// Source: queries/siteSettings.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{      navigation[] {        _key,        label,        "slug": page->slug.current,        iconType,        pixelIcon->{          title,          svg        },        "uploadedIcon": uploadedIcon.asset->url      },      footerText,      socialLinks[] {        platform,        url,        iconType,        pixelIcon->{          title,          svg        },        "uploadedIcon": uploadedIcon.asset->url      }    }
export type SiteSettingsQueryResult = {
  navigation: Array<{
    _key: string;
    label: string | null;
    slug: string | null;
    iconType: "image" | "pixel" | null;
    pixelIcon: {
      title: string | null;
      svg: string | null;
    } | null;
    uploadedIcon: string | null;
  }> | null;
  footerText: string | null;
  socialLinks: Array<{
    platform: string | null;
    url: string | null;
    iconType: "image" | "pixel" | null;
    pixelIcon: {
      title: string | null;
      svg: string | null;
    } | null;
    uploadedIcon: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n    *[_type == "article" && slug.current == $slug][0]{\n      title,\n      author->{\n        name,\n        avatar {\n          asset->{\n            url\n          }\n        },\n        bio,\n      },\n      body,\n      primaryCta->{\n        label,  \n        type,\n      },\n      coverImage {\n        asset->{\n          url,\n          metadata {\n            palette {\n              dominant {\n                background,\n                foreground,\n                population,\n              },\n              vibrant {\n                background,\n                foreground\n              },\n              muted {\n                background,\n                foreground\n              }\n            },\n            blurHash\n          }\n        }\n      },\n      backgroundPalette,\n      "palettes": {\n        "dominant": coverImage.asset->metadata.palette.dominant,\n        "vibrant": coverImage.asset->metadata.palette.vibrant,\n        "muted": coverImage.asset->metadata.palette.muted\n      },\n      isPrivate,\n      puzzle->{\n        title,\n        svg,\n        json\n      },\n      excerpt,\n      "pixel": icon->svg,\n      tagGroupSections[]{\n        heading,\n        groups[]{\n          emoji,\n          tags\n        }\n      }\n    }\n  ': ArticleQueryResult;
    '*[_type == "page" && slug.current == "/"][0]{\n  heading,\n  intro,\n  "themeColor": {\n    "h": coalesce(themeColor.hsl.h, 200),\n    "s": coalesce(themeColor.hsl.s * 100, 100),\n    "l": coalesce(themeColor.hsl.l * 100, 50)\n  },\n  pixelPuzzle->{\n    title,\n    svg,\n    json\n  },\n  "articles": *[_type == "article" && references(^._id)]{\n    _key,\n    "slug": slug.current,\n    title,\n    excerpt,\n    coverImage {\n      asset->{\n        url,\n        metadata {\n          palette {\n            dominant { background, foreground, population },\n            vibrant { background, foreground },\n            muted { background, foreground }\n          },\n          blurHash\n        }\n      }\n    }\n  }\n}\n': HomePageQueryResult;
    '*[_type == "siteSettings"][0]{\n      navigation[] {\n        _key,\n        label,\n        "slug": page->slug.current,\n        iconType,\n        pixelIcon->{\n          title,\n          svg\n        },\n        "uploadedIcon": uploadedIcon.asset->url\n      },\n      footerText,\n      socialLinks[] {\n        platform,\n        url,\n        iconType,\n        pixelIcon->{\n          title,\n          svg\n        },\n        "uploadedIcon": uploadedIcon.asset->url\n      }\n    }': SiteSettingsQueryResult;
  }
}
